//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenSistemaTG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int IdEquipo { get; set; }
        public int IdMarca { get; set; }
        public int IdModelo { get; set; }
        public string NoSerie { get; set; }
        public Nullable<int> Existencia { get; set; }
        public string Proveedor { get; set; }
        public int IdAlmacen { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
